In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("customer_sales_messy.csv")

In [ ]:
df

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [ ]:
df.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         53 non-null     int64
 1   Customer_Name    52 non-null     object
 2   City             51 non-null     object
 3   Product          53 non-null     object
 4   Category         52 non-null     object
 5   Quantity         53 non-null     int64
 6   Price            51 non-null     float64
 7   Order_Date       52 non-null     object
 8   Payment_Mode     52 non-null     object
 9   Salesperson      53 non-null     object
 10  Customer_Rating  51 non-null     float64
dtypes: float64(2), int64(2), object(7)
memory usage: 4.7+ KB

In [ ]:
df.shape

(53, 11)

In [ ]:
df.describe()

          Order_ID   Quantity         Price  Customer_Rating
count    53.000000  53.000000     51.000000        51.000000
mean   1024.584906   1.471698  10737.254902         4.196078
std      14.692272   0.696247  16851.970221         0.693386
min    1001.000000   1.000000    780.000000         3.000000
25%    1012.000000   1.000000   1975.000000         4.000000
50%    1024.000000   1.000000   3250.000000         4.000000
75%    1037.000000   2.000000   8350.000000         5.000000
max    1050.000000   4.000000  57000.000000         5.000000

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50     True
51     True
52    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df.drop_duplicates()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [ ]:
df.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Product', 'Category', 'Quantity',
       'Price', 'Order_Date', 'Payment_Mode', 'Salesperson',
       'Customer_Rating'],
      dtype='object')

In [ ]:
df.isnull().sum().sum()

np.int64(10)

In [ ]:
df[df.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [ ]:
missing = df.isnull().sum()

In [ ]:
missing_percentage = df.isnull().mean()*100

In [ ]:
df["City"] = df["City"].fillna("Unknown")

In [ ]:
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")

In [ ]:
df.isnull().sum()

Order_ID           0
Customer_Name      0
City               0
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [ ]:
df["Price"] = df["Price"].fillna(df["Price"].mean())

In [ ]:
df = df.dropna()

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Price, Order_Date, Payment_Mode, Salesperson, Customer_Rating]
Index: []

In [ ]:
df

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.000000,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.000000,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.000000,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.000000,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.000000,2026-09-03,CARD,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.000000,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.000000,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.000000,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,10737.254902,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.000000,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.000000,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,Unknown,Office Chair,Furniture,1,6200.000000,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.000000,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.000000,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.000000,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.000000,10/09/2026,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.000000,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.000000,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.000000,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.000000,2026-09-13,UPI,Meena,5.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.000000,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.000000,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.000000,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.000000,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.000000,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.000000,16/09/2026,card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.000000,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.000000,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.000000,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.000000,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.000000,19-09-2026,UPI,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.000000,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.000000,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.000000,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.000000,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,10737.254902,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.000000,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.000000,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.000000,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.000000,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.000000,2026-09-25,upi,Meena,5.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.000000,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,Unknown,Laptop Stand,Accessories,1,2150.000000,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.000000,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.000000,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.000000,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.000000,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.000000,2026-09-07,Card,Suresh,4.0

In [ ]:
f = pd.read_csv("customer_sales_messy.csv")

In [ ]:
f.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [ ]:
f_new = f.dropna(subset=["Customer_Name"])

In [ ]:
f_new.isnull().sum()

Order_ID           0
Customer_Name      0
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [ ]:
f[f.duplicated()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0

In [ ]:
f[f["Order_ID"]==1010]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [ ]:
df["City"].str.upper()

0       CHENNAI
1       CHENNAI
2       CHENNAI
3     BANGALORE
4     BENGALURU
5     HYDERABAD
6     HYDERABAD
7        MUMBAI
8        MUMBAI
9          PUNE
10         PUNE
11      UNKNOWN
12      CHENNAI
13        KOCHI
14        KOCHI
15      CHENNAI
17        DELHI
18    HYDERABAD
19       MUMBAI
20      CHENNAI
22    BENGALURU
23    HYDERABAD
24         PUNE
25        DELHI
26      KOLKATA
27      KOLKATA
29      CHENNAI
30      CHENNAI
31    HYDERABAD
32       MUMBAI
33       MUMBAI
35        DELHI
36      KOLKATA
37      KOLKATA
38        KOCHI
39      CHENNAI
40    BANGALORE
41    HYDERABAD
42        DELHI
43      CHENNAI
44      CHENNAI
46         PUNE
47      UNKNOWN
48        KOCHI
49    BENGALURU
50      CHENNAI
51        KOCHI
52         PUNE
Name: City, dtype: object

In [ ]:
f["City"].str.upper()

0       CHENNAI
1       CHENNAI
2       CHENNAI
3     BANGALORE
4     BENGALURU
5     HYDERABAD
6     HYDERABAD
7        MUMBAI
8        MUMBAI
9          PUNE
10         PUNE
11          NaN
12      CHENNAI
13        KOCHI
14        KOCHI
15      CHENNAI
16        DELHI
17        DELHI
18    HYDERABAD
19       MUMBAI
20      CHENNAI
21    BANGALORE
22    BENGALURU
23    HYDERABAD
24         PUNE
25        DELHI
26      KOLKATA
27      KOLKATA
28        KOCHI
29      CHENNAI
30      CHENNAI
31    HYDERABAD
32       MUMBAI
33       MUMBAI
34         PUNE
35        DELHI
36      KOLKATA
37      KOLKATA
38        KOCHI
39      CHENNAI
40    BANGALORE
41    HYDERABAD
42        DELHI
43      CHENNAI
44      CHENNAI
45         PUNE
46         PUNE
47          NaN
48        KOCHI
49    BENGALURU
50      CHENNAI
51        KOCHI
52         PUNE
Name: City, dtype: object

In [ ]:
f_new["City"] = f_new["City"].str.upper()

/tmp/ipykernel_1254/2482477327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_new["City"] = f_new["City"].str.upper()

In [ ]:
f_new

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,CHENNAI,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,CHENNAI,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,BANGALORE,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,BENGALURU,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,MUMBAI,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,MUMBAI,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,PUNE,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,PUNE,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,CHENNAI,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,KOCHI,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,CHENNAI,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,DELHI,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,DELHI,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,HYDERABAD,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,MUMBAI,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,CHENNAI,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,BANGALORE,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,BENGALURU,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,HYDERABAD,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,PUNE,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,DELHI,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,KOLKATA,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,KOLKATA,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,KOCHI,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,CHENNAI,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,CHENNAI,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,HYDERABAD,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,MUMBAI,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,MUMBAI,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,PUNE,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,DELHI,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,KOLKATA,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,KOLKATA,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,KOCHI,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,CHENNAI,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,BANGALORE,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,HYDERABAD,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,DELHI,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,CHENNAI,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,PUNE,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,PUNE,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,KOCHI,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,BENGALURU,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,PUNE,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [ ]:
f_new["City"].unique()

array(['CHENNAI', ' CHENNAI', 'BANGALORE', 'BENGALURU', 'HYDERABAD',
       'MUMBAI', 'PUNE', nan, 'KOCHI', 'DELHI', 'KOLKATA'], dtype=object)

In [ ]:
f_new["City"] = f_new["City"].str.strip()

/tmp/ipykernel_1254/358626157.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_new["City"] = f_new["City"].str.strip()

In [ ]:
f_new["Customer_Name"] = f_new["Customer_Name"].str.title()

/tmp/ipykernel_1254/306779325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_new["Customer_Name"] = f_new["Customer_Name"].str.title()

In [ ]:
f_new["Customer_Name"]

0        Arun Kumar
1       Priya Sharma
2        Rahul Verma
3          Divya Raj
4          Karthik S
6        Vijay Kumar
7         Anjali Rao
8        Manoj Patel
9          Asha Nair
10         Rohit Das
11        Neha Singh
12        Arun Kumar
13       Pooja Menon
14          Ramesh B
15        Sanjay Rao
16      Lakshmi Devi
17        Ajay Kumar
18    Meena Krishnan
19        Varun Shah
20          Nithya S
21       Rakesh Jain
22         Keerthi M
23      Suresh Kumar
24        Pavithra R
25         Gokul Raj
26        Ishita Sen
27      Deepak Singh
28        Anu Joseph
29          Naveen P
30          Sowmya R
31        Hari Krish
32       Swathi Rao
33         Prakash N
34          Geetha S
35         Mohan Raj
36       Riya Kapoor
37        Abhishek T
38        Farah Khan
39          Naveen P
40         Divya Raj
41        Siva Kumar
42         Anita Roy
43       Rahul Verma
44      Priya Sharma
45           Kiran B
46         Rohit Das
47         Asha Nair
48            Maya S
49          Vikram J
50       Rahul Verma
51          Ramesh B
52         Rohit Das
Name: Customer_Name, dtype: object

In [ ]:
f_new["Payment_Mode"].unique()

array([' cash ', 'UPI', 'upi', 'Card', 'CARD ', 'cash', 'Cash', 'card',
       nan, ' Cash', 'CARD'], dtype=object)

In [ ]:
df["Payment_Mode"].unique()

array([' cash ', 'UPI', 'upi', 'Card', 'CARD ', 'Cash', 'cash', 'card',
       ' Cash', 'CARD'], dtype=object)

In [ ]:
df["Payment_Mode"] = df["Payment_Mode"].str.title()

/tmp/ipykernel_1254/2362997007.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_Mode"] = df["Payment_Mode"].str.title()

In [ ]:
df["Payment_Mode"] = df["Payment_Mode"].str.strip()

/tmp/ipykernel_1254/2602930733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_Mode"] = df["Payment_Mode"].str.strip()

In [ ]:
df.head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [ ]:
df["Customer.name"] = (df["Customer_Name"].str.strip().str.title())
df.head()

/tmp/ipykernel_1254/1534043197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Customer.name"] = (df["Customer_Name"].str.strip().str.title())

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Customer.name
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0,Arun Kumar
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0,Priya Sharma
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0,Rahul Verma
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0,Divya Raj
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0,Karthik S

In [ ]:
df["City"] = (df["City"].str.strip().str.title())
df.head()

/tmp/ipykernel_1254/1202562116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = (df["City"].str.strip().str.title())

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Customer.name
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0,Arun Kumar
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0,Priya Sharma
2,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0,Rahul Verma
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0,Divya Raj
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0,Karthik S

In [ ]:
df["City"]=df["City"].str.replace("Bengaluru","Bangalore")
df.head()

/tmp/ipykernel_1254/2274752088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"]=df["City"].str.replace("Bengaluru","Bangalore")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Customer.name
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0,Arun Kumar
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0,Priya Sharma
2,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0,Rahul Verma
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0,Divya Raj
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0,Karthik S

In [ ]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"],errors="coerce")
df.head()

/tmp/ipykernel_1254/1050031266.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order_Date"] = pd.to_datetime(df["Order_Date"],errors="coerce")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Customer.name
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0,Arun Kumar
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,NaT,Upi,Meena,5.0,Priya Sharma
2,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0,Rahul Verma
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,NaT,Card,Suresh,3.0,Divya Raj
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0,Karthik S

In [ ]:
df["Order_Date"].isnull().sum()

np.int64(26)

In [ ]:
df[df["Order_Date"].isnull()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Customer.name
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.000000,NaT,Upi,Meena,5.0,Priya Sharma
2,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.000000,NaT,Upi,Ravi,4.0,Rahul Verma
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.000000,NaT,Card,Suresh,3.0,Divya Raj
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.000000,NaT,Cash,Ravi,4.0,Unknown
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.000000,NaT,Upi,Meena,5.0,Anjali Rao
10,1011,Rohit Das,Pune,Monitor,Electronics,1,11800.000000,NaT,Cash,Meena,5.0,Rohit Das
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.000000,NaT,Card,Suresh,5.0,Pooja Menon
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.000000,NaT,Cash,Ravi,3.0,Sanjay Rao
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.000000,NaT,Upi,Meena,5.0,Ajay Kumar
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.000000,NaT,Card,Suresh,3.0,Varun Shah
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.000000,NaT,Cash,Meena,5.0,Suresh Kumar
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.000000,NaT,Upi,Suresh,3.0,Gokul Raj
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.000000,NaT,Card,Ravi,4.0,Deepak Singh
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.000000,NaT,Cash,Meena,4.0,Naveen P
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.000000,NaT,Card,Suresh,4.0,Hari Krish
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.000000,NaT,Cash,Meena,3.0,Swathi Rao
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.000000,NaT,Upi,Ravi,4.0,Prakash N
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.000000,NaT,Cash,Meena,4.0,Mohan Raj
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.000000,NaT,Card,Suresh,4.0,Abhishek T
39,1040,Naveen P,Chennai,Mouse,Electronics,2,10737.254902,NaT,Upi,Ravi,4.0,Naveen P
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.000000,NaT,Cash,Meena,4.0,Siva Kumar
43,1044,Rahul Verma,Chennai,Laptop,Electronics,1,55500.000000,NaT,Card,Suresh,4.0,Rahul Verma
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.000000,NaT,Card,Suresh,3.0,Rohit Das
47,1048,Asha Nair,Unknown,Laptop Stand,Accessories,1,2150.000000,NaT,Upi,Meena,5.0,Asha Nair
49,1050,Vikram J,Bangalore,Office Chair,Furniture,1,6600.000000,NaT,Card,Suresh,5.0,Vikram J
50,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.000000,NaT,Upi,Ravi,4.0,Rahul Verma

In [ ]:
df["Order_Date"]=df["Order_Date"].fillna("2026-01-01")

/tmp/ipykernel_1254/1422532818.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order_Date"]=df["Order_Date"].fillna("2026-01-01")

In [ ]:
df["Order_Date"].dt.date

0     2026-09-01
1     2026-01-01
2     2026-01-01
3     2026-01-01
4     2026-09-03
5     2026-01-01
6     2026-09-05
7     2026-01-01
8     2026-09-06
9     2026-09-07
10    2026-01-01
11    2026-09-08
12    2026-09-01
13    2026-01-01
14    2026-09-10
15    2026-01-01
17    2026-01-01
18    2026-09-12
19    2026-01-01
20    2026-09-13
22    2026-09-14
23    2026-01-01
24    2026-09-15
25    2026-01-01
26    2026-09-16
27    2026-01-01
29    2026-01-01
30    2026-09-18
31    2026-01-01
32    2026-01-01
33    2026-01-01
35    2026-01-01
36    2026-09-21
37    2026-01-01
38    2026-09-22
39    2026-01-01
40    2026-09-23
41    2026-01-01
42    2026-09-24
43    2026-01-01
44    2026-09-25
46    2026-01-01
47    2026-01-01
48    2026-09-27
49    2026-01-01
50    2026-01-01
51    2026-09-10
52    2026-09-07
Name: Order_Date, dtype: object

In [ ]:
df

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Customer.name
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.000000,2026-09-01,Cash,Ravi,4.0,Arun Kumar
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.000000,2026-01-01,Upi,Meena,5.0,Priya Sharma
2,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.000000,2026-01-01,Upi,Ravi,4.0,Rahul Verma
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.000000,2026-01-01,Card,Suresh,3.0,Divya Raj
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.000000,2026-09-03,Card,Meena,5.0,Karthik S
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.000000,2026-01-01,Cash,Ravi,4.0,Unknown
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.000000,2026-09-05,Cash,Suresh,4.0,Vijay Kumar
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.000000,2026-01-01,Upi,Meena,5.0,Anjali Rao
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,10737.254902,2026-09-06,Upi,Ravi,3.0,Manoj Patel
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.000000,2026-09-07,Card,Suresh,4.0,Asha Nair
10,1011,Rohit Das,Pune,Monitor,Electronics,1,11800.000000,2026-01-01,Cash,Meena,5.0,Rohit Das
11,1012,Neha Singh,Unknown,Office Chair,Furniture,1,6200.000000,2026-09-08,Upi,Ravi,4.0,Neha Singh
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.000000,2026-09-01,Cash,Ravi,4.0,Arun Kumar
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.000000,2026-01-01,Card,Suresh,5.0,Pooja Menon
14,1015,Ramesh B,Kochi,Mouse,Electronics,3,800.000000,2026-09-10,Upi,Meena,4.0,Ramesh B
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.000000,2026-01-01,Cash,Ravi,3.0,Sanjay Rao
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.000000,2026-01-01,Upi,Meena,5.0,Ajay Kumar
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.000000,2026-09-12,Cash,Ravi,4.0,Meena Krishnan
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.000000,2026-01-01,Card,Suresh,3.0,Varun Shah
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.000000,2026-09-13,Upi,Meena,5.0,Nithya S
22,1023,Keerthi M,Bangalore,Keyboard,Electronics,1,1900.000000,2026-09-14,Upi,Suresh,4.0,Keerthi M
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.000000,2026-01-01,Cash,Meena,5.0,Suresh Kumar
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.000000,2026-09-15,Card,Ravi,4.0,Pavithra R
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.000000,2026-01-01,Upi,Suresh,3.0,Gokul Raj
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.000000,2026-09-16,Cash,Meena,5.0,Ishita Sen
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.000000,2026-01-01,Card,Ravi,4.0,Deepak Singh
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.000000,2026-01-01,Cash,Meena,4.0,Naveen P
30,1031,Sowmya R,Chennai,Office Chair,Furniture,2,6300.000000,2026-09-18,Upi,Ravi,5.0,Sowmya R
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.000000,2026-01-01,Card,Suresh,4.0,Hari Krish
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.000000,2026-01-01,Cash,Meena,3.0,Swathi Rao
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.000000,2026-01-01,Upi,Ravi,4.0,Prakash N
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.000000,2026-01-01,Cash,Meena,4.0,Mohan Raj
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.000000,2026-09-21,Upi,Ravi,5.0,Riya Kapoor
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.000000,2026-01-01,Card,Suresh,4.0,Abhishek T
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.000000,2026-09-22,Cash,Meena,5.0,Farah Khan
39,1040,Naveen P,Chennai,Mouse,Electronics,2,10737.254902,2026-01-01,Upi,Ravi,4.0,Naveen P
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.000000,2026-09-23,Card,Suresh,3.0,Divya Raj
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.000000,2026-01-01,Cash,Meena,4.0,Siva Kumar
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.000000,2026-09-24,Upi,Ravi,5.0,Anita Roy
43,1044,Rahul Verma,Chennai,Laptop,Electronics,1,55500.000000,2026-01-01,Card,Suresh,4.0,Rahul Verma
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.000000,2026-09-25,Upi,Meena,5.0,Priya Sharma
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.000000,2026-01-01,Card,Suresh,3.0,Rohit Das
47,1048,Asha Nair,Unknown,Laptop Stand,Accessories,1,2150.000000,2026-01-01,Upi,Meena,5.0,Asha Nair
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.000000,2026-09-27,Cash,Ravi,4.0,Maya S
49,1050,Vikram J,Bangalore,Office Chair,Furniture,1,6600.000000,2026-01-01,Card,Suresh,5.0,Vikram J
50,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.000000,2026-01-01,Upi,Ravi,4.0,Rahul Verma
51,1015,Ramesh B,Kochi,Mouse,Electronics,3,800.000000,2026-09-10,Upi,Meena,4.0,Ramesh B
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.000000,2026-09-07,Card,Suresh,4.0,Rohit Das

In [ ]:
df["Quantity"] = pd.to_numeric(df["Quantity"],errors="coerce")
df.head()

/tmp/ipykernel_1254/606069965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Quantity"] = pd.to_numeric(df["Quantity"],errors="coerce")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Customer.name
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0,Arun Kumar
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0,Priya Sharma
2,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0,Rahul Verma
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0,Divya Raj
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0,Karthik S

In [ ]:
df[df["Quantity"].isnull()]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Price, Order_Date, Payment_Mode, Salesperson, Customer_Rating, Customer.name]
Index: []

In [ ]:
df.dtypes

Order_ID                    int64
Customer_Name              object
City                       object
Product                    object
Category                   object
Quantity                    int64
Price                     float64
Order_Date         datetime64[ns]
Payment_Mode               object
Salesperson                object
Customer_Rating           float64
Customer.name              object
dtype: object

In [ ]:
df["Total_sales"] =(df["Quantity"]*df["Price"])
df.head()

/tmp/ipykernel_1254/3777816516.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total_sales"] =(df["Quantity"]*df["Price"])

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Customer.name,Total_sales
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0,Arun Kumar,55000.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0,Priya Sharma,1700.0
2,1003,RAHUL VERMA,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0,Rahul Verma,1800.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0,Divya Raj,12500.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0,Karthik S,13000.0

In [ ]:
df.isnull().sum()

Order_ID           0
Customer_Name      0
City               0
Product            0
Category           0
Quantity           0
Price              0
Order_Date         0
Payment_Mode       0
Salesperson        0
Customer_Rating    0
Customer.name      0
Total_sales        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["City"].value_counts()

City
Chennai      11
Hyderabad     6
Bangalore     5
Mumbai        5
Pune          5
Kochi         4
Delhi         4
Kolkata       4
Unknown       2
Name: count, dtype: int64

In [ ]:
print(df["City"].value_counts())

City
Chennai      11
Hyderabad     6
Bangalore     5
Mumbai        5
Pune          5
Kochi         4
Delhi         4
Kolkata       4
Unknown       2
Name: count, dtype: int64

In [ ]:
df.groupby("Product")["Total_sales"].sum()

Product
Desk             32200.000000
Headphones       21937.254902
Keyboard         14350.000000
Laptop          332500.000000
Laptop Stand     19400.000000
Monitor          72700.000000
Mouse            32214.509804
Office Chair     50900.000000
Webcam           22350.000000
Name: Total_sales, dtype: float64

In [ ]:
new_table = pd.DataFrame(df.groupby("Product")["Total_sales"].sum())

In [ ]:
new_table.sort_values(by="Total_sales",ascending=False)

                Total_sales
Product
Laptop        332500.000000
Monitor        72700.000000
Office Chair   50900.000000
Mouse          32214.509804
Desk           32200.000000
Webcam         22350.000000
Headphones     21937.254902
Laptop Stand   19400.000000
Keyboard       14350.000000

In [ ]:
Sales_by_Category = pd.DataFrame(df.groupby("Quantity")["Total_sales"].sum())

In [ ]:
Sales_by_Category

            Total_sales
Quantity
1         470687.254902
2         116034.509804
3           8550.000000
4           3280.000000

In [ ]:
df.groupby("City").agg(Orders = ("Order_ID", "count"), Total_Sales = ("Total_sales", "sum"), average_Rating = ("Customer_Rating","mean"))

           Orders    Total_Sales  average_Rating
City
Bangalore       5   35800.000000        4.000000
Chennai        11  235974.509804        4.272727
Delhi           4   20250.000000        4.250000
Hyderabad       6   80130.000000        4.166667
Kochi           4   19660.000000        4.500000
Kolkata         4  127700.000000        4.500000
Mumbai          5   42887.254902        3.600000
Pune            5   27800.000000        4.000000
Unknown         2    8350.000000        4.500000

In [ ]:
df.to_csv("Customer_Dataset_cleaned.csv",index=False)